spring.application.name=springboot1-1

# ==== Ket noi SQL Server (dung chung style voi cac project truoc) ====
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=springboot1;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD:60021051}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==== JPA / Hibernate ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==== View resolver cho JSP ====
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ==== Gui mail OTP qua Gmail SMTP ====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:} //mail
spring.mail.password=${MAIL_PASSWORD:} //app passwork
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==== Upload file ====
app.upload.dir=D:/upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

server.port=8080
